const cities = [
  'Hong Kong',
  'Bangkok',
  'London',
  'Macau',
  'Singapore',
  'Paris',
  'New York',
  'Kuala Lumpur',
  'Istanbul',
  'Delhi',
  'Shenzhen',
  'Phuket',
  'Rome',
  'Tokyo',
  'Pattaya',
  'Taipei',
  'Mecca',
  'Guangzhou',
  'Prague',
  'Medina',
  'Seoul',
  'Amsterdam',
  'Agra',
  'Miami',
  'Osaka',
  'Las Vegas',
  'Ho Chi Minh',
  'Denpasar',
  'Barcelona',
  'Los Angeles',
  'Milan',
  'Chennai',
  'Vienna',
  'Jaipur',
  'Cairo',
  'Orlando',
  'Moscow',
  'Venice',
  'Madrid',
  'Ha Long',
  'Riyadh',
  'Dublin',
  'Florence',
  'Jerusalem',
  'Hanoi',
  'Johannesburg',
  'Sydney',
  'Munich',
  'Jakarta',
  'Beijing',
  'Saint Petersburg',
  'Brussels',
  'Budapest',
  'Lisbon',
  'Kyoto',
  'Zhihan',
  'Vancouver',
  'Copenhagen',
  'San Francisco',
  'Warsaw',
  'Marrakesh',
  'Krakow',
  'Buenos Aires',
  'Porto',
  'Zurich',
  'Boston',
  'Edinburgh',
  'Chengdu',
  'San Jose',
  'Tehran',
  'Hamburg',
  'Houston',
  'Sofia',
  'Montevideo',
  'Tianjin',
  'Dallas',
  'Qingdao',
  'Tianjin',
];

const apiKey = '1c56d6bcb63bcb9311ad7885c935c603';
const weatherApiUrl = 'https://api.openweathermap.org/data/2.5/weather';